// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go_todo_api/internal/controller"
	"go_todo_api/internal/repository"
	"go_todo_api/internal/router"
	"go_todo_api/internal/service"
	"go_todo_api/internal/validator"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializeServer() (*http.Server, func()) {
	db, cleanup := NewDB()
	userRepository := repository.NewUserRepository()
	validate := validator.NewValidator()
	userService := service.NewUserService(db, userRepository, validate)
	userController := controller.NewUserController(userService)
	todoRepository := repository.NewTodoRepository()
	todoService := service.NewTodoService(db, todoRepository, validate)
	todoController := controller.NewTodoController(todoService)
	authService := service.NewAuthService(db, userRepository, validate)
	authController := controller.NewAuthController(authService)
	httprouterRouter := router.NewRouter(userController, todoController, authController)
	server := NewServer(httprouterRouter)
	return server, func() {
		cleanup()
	}
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)

var authSet = wire.NewSet(service.NewAuthService, controller.NewAuthController)

var todoSet = wire.NewSet(repository.NewTodoRepository, service.NewTodoService, controller.NewTodoController)
